spring.application.name=TokendustryAPI

spring.datasource.url=jdbc:mysql://localhost:3306/tokendustry?useSSL=false&serverTimezone=UTC
spring.datasource.username=Zephose
spring.datasource.password=STUCKPLAT2FOREVER

#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
server.port=8080

#POUR LANCER L'API -> /mvnw spring-boot:run